#!/usr/bin/env task
# yaml-language-server: $schema=https://taskfile.dev/schema.json
#
# See https://taskfile.dev/installation/ for install instructions.
#
#   $> brew install go-task/tap/go-task
#   $> scoop install task
#   $> pkgx task
#   $> sudo snap install task --classic
#
# cspell:ignore pkgx

version: "3"

tasks:
  default:
    cmds:
      - task: serve

  serve:
    cmds:
      - cmd: cargo run -- serve

  publish:
    cmds:
      - cmd: cargo publish --registry github --token $(CARGO_REGISTRY_TOKEN)

  git-clean:
    vars:
      CLOSE_STDIN: '{{if eq OS "windows"}}<nul{{else}}0<&-{{end}}'
    cmds:
      - cmd: git add .
      - cmd: git clean -xfd {{.CLOSE_STDIN}}
        silent: true
        ignore_error: true
  
  release-arm64:
    cmds:
      # run this on m1-based macOS
      - cmd: | # shell
          set -ex

          v=$(grep version Cargo.toml | head -1 | awk '{print $3}' | tr -d '"')

          rm -rf 1History*zip 1History*zip.sha256sum
          cargo build --release
          cp -f target/release/onehistory .
          zip 1History_v"${v}"_aarch64-apple-darwin.zip onehistory README.org
          sha256sum 1History_v"${v}"_aarch64-apple-darwin.zip > 1History_v"${v}"_aarch64-apple-darwin.zip.sha256sum
