#!/usr/bin/env task
# yaml-language-server: $schema=https://taskfile.dev/schema.json
#
# See https://taskfile.dev/installation/ for install instructions.
#
#   $> brew install go-task/tap/go-task
#   $> scoop install task
#   $> pkgx task
#   $> sudo snap install task --classic
#
# cspell:ignore pkgx

version: "3"

vars:
  APP_NAME: 1History
  EXE_NAME: onehistory

tasks:
  default:
    cmds:
      - task: serve

  serve:
    cmds:
      - cmd: cargo run -- serve

  publish:
    deps: [org-to-markdown]
    cmds:
      - cmd: cargo publish --registry github --token $(CARGO_REGISTRY_TOKEN)

  git-clean:
    vars:
      CLOSE_STDIN: '{{if eq OS "windows"}}<nul{{else}}0<&-{{end}}'
    cmds:
      - cmd: git add .
      - cmd: git clean -xfd {{.CLOSE_STDIN}}
        silent: true
        ignore_error: true
  
  org-to-markdown:
    cmds:
      - cmd: pandoc -f org -t markdown README.org -o README.md

  clean:
    status:
      - test ! -f {{.APP_NAME}}*zip
      - test ! -f {{.APP_NAME}}*zip.sha256sum
      - test ! -f {{.EXE_NAME}}
    cmds:
      - cmd: >-
          rm -rf
          {{.APP_NAME}}*zip 
          {{.APP_NAME}}*zip.sha256sum 
          "{{.EXE_NAME}}"
        platforms: [linux, darwin]

  release-arm64:
    deps: [org-to-markdown]
    vars:
      VERSION:
        sh: grep version Cargo.toml | head -1 | awk '{print $3}' | tr -d '"'
      ARCHIVE_NAME: '{{.APP_NAME}}_v{{.VERSION}}_aarch64-apple-darwin.zip'
      ARCHIVE_HASH_NAME: '{{.ARCHIVE_NAME}}.sha256sum'
      ARCHIVE_PATH: '{{joinPath .TASKFILE_DIR .ARCHIVE_NAME}}'
      ARCHIVE_HASH_PATH: '{{joinPath .TASKFILE_DIR .ARCHIVE_HASH_NAME}}'
    status:
      - test -f "{{.ARCHIVE_PATH}}"
      - test -f "{{.ARCHIVE_HASH_PATH}}"
    preconditions:
      - zip --version
      - cp --version
      - cargo --version
      - sha256sum --version
    sources:
      - README.org
      - Cargo.toml
      - src/**
    generates:
      - "{{.ARCHIVE_PATH}}"
      - "{{.ARCHIVE_PATH}}.sha256sum"
    cmds:
      # run this on m1-based macOS
      - task: clean
      - cmd: |
          cargo build --release
      - cmd: |
          cp -f target/release/onehistory .
        platforms: [linux, darwin]
      - cmd: |
          zip "{{.ARCHIVE_PATH}}" {{.EXE_NAME}} README.md
        platforms: [linux, darwin]
      - cmd: |
          sha256sum "{{.ARCHIVE_PATH}}" > "{{.ARCHIVE_PATH}}.sha256sum"
        platforms: [linux, darwin]

